### PR TITLE
TCP/IP server support

### PR DESCRIPTION
**Pull request by bernhard-thiele**
PR for #295.

### CODE REVIEW

**Comment by bernhard-thiele** [comment]
@tbeu The PR should be fine now and is ready to be merged in. I tested with Dymola on Windows and with OpenModelica on Windows and Linux. If you like you can check if everything works for SimulationX, too.

**Comment by tbeu** [comment]
Will do. What is the timeline for v1.8.0?

**Comment by bernhard-thiele** [comment]
The end of the first October week seems realistic (without STM32 support). Should maybe have a milestone "undecided" for features where the timeline is very unclear.

**Comment by bernhard-thiele** [comment]
Thanks for the review and the fixes!

Unfortunately, I didn't manage to finalize the release last week, there were unplanned issues which reduced my free time. So hopefully I'll release something until the end of this week.

I'm not sure regarding the proposed renaming of the functions. The naming is not completely consistent in the library. We have a consistent prefix `MDD_`, after that there is usually a string denoting the "class", e.g., `MDD_udpSend`. But sometimes the "class" is lowercase, sometimes upper case, e.g., `MDD_SharedMemoryRead`, sometimes there is a `_` as delimiter starting with lower case, e.g., `MDD_avr_rt_init`, or with uppercase `MDD_TCPIPClient_Send`. I prefer lower case for the "function" part (if using the `_` delimeter), but have no strong opinion about it. Since the functions in `MDD_TCPIPClient` already use upper case, we can do the same for `MDD_TCPIPServer`.

**Pull request merged**
