### PR TITLE
Use folders in generated VS projects

### PR DESCRIPTION
**Pull request by bernhard-thiele**
Generating a VS Studio 2017 project with cmake will use folders for structuring the project:

grafik

In addition the PR sets the minimum required cmake version to 3.12.0, allowing more modern cmake constructs.

### CODE REVIEW

**Comment by beutlich** [comment]
There was some reason to have CMake required at v2.8.12 (to support some Ubuntu LTS if I recall correctly). Will this support be dropped now intentionally? @sjoelund

**Comment by bernhard-thiele** [comment]
I don't remember if there was a reason to stick at v2.8.12. For the moment I just want to use this folder feature to get a nicer project outline in VS. I need to check at which cmake version this feature was available, maybe already in v2.8.12. However, for the future I'd also like to experiment with more recent cmake features, e.g., supporting a nice integration of googletest into the project.

**Comment by sjoelund** [comment]
cmake 3.12.0 will not compile in any Ubuntu LTS release (it's only in the recently released 19.04). We still support CentOS 6, which has cmake 2.8.12 only.

Note that it is often possible to make the cmake project aware of the older version and only use the new features if the version is high enough. It should also be possible with like `cmake_minimum_required(VERSION 2.8.12...3.12.0)` according to https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html. That in particular should remove some old policy messages.

**Comment by bernhard-thiele** [comment]
Okay, the cmake change in the commit seems to work with v2.8.12. The CI checks failed due to some unrelated connection problems with the (external) MQTT test server.

I will try to keep the build compatible to v2.8.12, though the cmake requirement shouldn't be an issue for standard Modelica library users. It's only needed if rebuilding the external libs, which we deliver anyway as binaries for all supported platforms, is desired.

**Pull request merged**
