### PR TITLE
Experiment using googletest for unit testing

### PR DESCRIPTION
**Pull request by bernhard-thiele**
- Googletest library sources added below Resources/thirdParty/googletest
- Added Resources/test/OperatingSystem/test_MDDRealtimeSynchronize.cpp
  as googletest usage example (all test_MDDRealtimeSynchronize_* as
  unit tests)
- Related to cmake versioning discussion in #286

### CODE REVIEW

**Comment by bernhard-thiele** [comment]
@tbeu @sjoelund  After quite a few tries, I think I have found a reasonable solution for integrating Googletest. Only the last (forced-pushed) commit is relevant, it squashes together all previous experiments. The scripts use more modern CMake features where available, while at the same time maintaining backwards compatibility to CMake v2.8.12 (#286).

I've integrated the Googletest test into the travis.yml  file:

```
sudo ./test_MDDRealtimeSynchronize
```
Instead of executing the test binaries individually, we could also use ctest for executing the whole suite, e.g., by adding the line (the `-E` option excludes the tests which are unsuitable for CI at the moment):

```
 - sudo /opt/cmake-2.8.12.2-Linux-i386/bin/ctest --output-on-failure -E "MDDSpaceMouse|MDDTCPIPSocketClient|MDDSerialPort|MDDBeep|MDDSocketCAN"
```

This is a bit a matter of taste.

As a next step the individual binaries for the real-time synchronization tests `test_MDDRealtimeSynchroniz_*` can be removed, because the new Googletest driven `test_MDDRealtimeSynchronize.cpp` collects all those tests in one file.

@tbeu What do you prefer?

**Comment by tbeu** [comment]
I'd prefer to add the gtest files as git submodule (instead of adding hundreds of new files directly to the repository).

**Comment by bernhard-thiele** [comment]
Okay, I added it as a submodule.

As often it is about finding good compromises, what I don't like with submodules is:

- Not as easy to use for the uninitiated
- Exporting the git project to a ZIP (`git archive ...`) as I do for cutting the releases, does not export the files in the submodule

Below a note how I added googletest

```
git submodule add --name gtest ../../google/googletest.git Modelica_DeviceDrivers/Resources/thirdParty/googletest
git commit -a -m "Add googletest as submodule"
cd Modelica_DeviceDrivers/Resources/thirdParty/googletest/
git tag -l
git checkout release-1.8.1
cd ..
add googletest
git commit -m "Move googletest submodule to release-1.8.1"
```

**Comment by bernhard-thiele** [comment]
Wrote a shell script which allows to export a source archive including the files from the googletest submodule.

The script works also in the git bash which is shipped with the Windows TortoiseGit client, except that the `zip` executable is missing in a standard installation. The script looks like:

```bash
MDDVERSION="1.6.0"
MDDVERSIONV="v1_6_0"

# Below there should be no need for changes
MDDPREFIX="Modelica_DeviceDrivers $MDDVERSION"
MDDARCHIVE_TAR="Modelica_DeviceDrivers_$MDDVERSIONV.tar"
MDDARCHIVE_ZIP="Modelica_DeviceDrivers_$MDDVERSIONV.zip"
git archive -o $MDDARCHIVE_TAR --prefix="$MDDPREFIX/" HEAD:Modelica_DeviceDrivers/
cd Modelica_DeviceDrivers/Resources/thirdParty/googletest/
git archive -o googletest.tar --prefix="$MDDPREFIX/Resources/thirdParty/googletest/"  HEAD
cd ../../../..
mv Modelica_DeviceDrivers/Resources/thirdParty/googletest/googletest.tar .
tar --concatenate --file=$MDDARCHIVE_TAR googletest.tar
mkdir tmp_archive
tar -C tmp_archive -xf "$MDDARCHIVE_TAR"
cd tmp_archive
zip -9 -r $MDDARCHIVE_ZIP "$MDDPREFIX/"
mv $MDDARCHIVE_ZIP ..
cd ..
gzip -9 -v $MDDARCHIVE_TAR
rm googletest.tar
rm -r tmp_archive
```

**Pull request merged**
